# Generated by Django 5.0.3 on 2024-03-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoEliminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('obra', models.CharField(max_length=100)),
                ('num_identificacion', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empleado eliminado',
                'verbose_name_plural': 'empleados eliminados',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Obra')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Puesto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo Base')),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('num_identificacion', models.IntegerField(verbose_name='Número de Identificación')),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias_obras.obra', verbose_name='Obra')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias_obras.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
            },
        ),
    ]
