# Generated by Django 2.2.12 on 2024-03-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0006_auto_20240309_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias_obras.Obra', verbose_name='Obra'),
        ),
    ]
