# Generated by Django 5.0.3 on 2024-03-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0008_obra_presupuesto_alter_empleado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
