# Generated by Django 2.2.12 on 2024-03-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0010_empleado_fotografia_empleadoeliminado_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_qr_empleados/', verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='empleadoeliminado',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_qr_empleados/', verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleadoeliminado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
