# Generated by Django 4.2.11 on 2024-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0013_alter_asistencia_id_alter_empleado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_asistencia/'),
        ),
    ]
