# Generated by Django 5.0.3 on 2024-03-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0015_milestone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
