# Generated by Django 5.0.3 on 2024-04-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0016_delete_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='obra',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='obra',
            field=models.ManyToManyField(blank=True, to='asistencias_obras.obra', verbose_name='Obras'),
        ),
    ]
