# Generated by Django 5.0.3 on 2024-04-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0018_remove_userprofile_obra_userprofile_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='obra',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='obras',
            field=models.ManyToManyField(blank=True, to='asistencias_obras.obra', verbose_name='Obras'),
        ),
    ]
