# Generated by Django 4.2.11 on 2024-04-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0019_remove_userprofile_obra_userprofile_obras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencias_obras.empleado'),
        ),
    ]
