# Generated by Django 4.2.11 on 2024-04-30 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias_obras', '0021_alter_asistencia_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencias_obras.empleado'),
        ),
    ]
